// ARCHIVO GENERADO — no editar a mano.
//
// Catálogos de nómina de Ingeniería SIMA, sacados de
// `docs/Puestos y listado de personal.xlsx`: la hoja "Listado de Puestos" y los
// valores distintos de la columna "Dependencia" de la hoja de nómina (que es
// como la empresa llama a lo que acá es centro de costo).
//
// Del Excel de nómina se lleva SOLO esto. Las 530 filas de personas —legajo,
// DNI y apellido y nombre— son PII y no entran a ningún archivo versionado:
// se cargan desde el import de Excel del backoffice.

// Los 88 puestos de la hoja "Listado de Puestos", en su orden.
export const PUESTOS: string[] = [
  'Administrativo/a',
  'Albañil',
  'Amolador',
  'Apuntador de QA/QC',
  'Auxiliar Tesorería',
  'Auxiliar Comprador',
  'Auxiliar de Deposito',
  'Auxiliar de Sistemas Informáticos',
  'Auxiliar QA/QC',
  'Ayte. de Recorredor',
  'Ayte. OP de planta',
  'Ayte. Tareas Generales',
  'Baterista',
  'Cañista',
  'Chapista-Pintor',
  'Chofer flota pesada',
  'Chofer flota pesada C/ Hidro',
  'Chofer flota semi pesada',
  'Chofer flota semi pesada C/ Hidro',
  'Compresorista',
  'Contador P. Nac',
  'Control de Calidad',
  'Control Documental QA/QC',
  'Coord. de Servicio',
  'Coord. Logística',
  'Coord. SSMAC',
  'Cotizador',
  'Electricista Automotor',
  'Electricista de Campo',
  'Electromecánico',
  'Fiscalizador de despacho',
  'Gammagrafía',
  'Gerente Comercial',
  'Gerente de Ingeniería y QAQC',
  'Gerente de Taller',
  'Gerente Proyectos',
  'Gerente Servicios',
  'Gerente SSMAC',
  'Gruista',
  'Herrero',
  'Instrumentista',
  'Invitado Sima Check',
  'Jefe de Obra',
  'Jefe de Taller',
  'Laboratorista',
  'Maestranza',
  'Mecánico Automotor',
  'Mecánico de Campo',
  'Médico Laboral',
  'Montador Eléctrico',
  'Montador Eléctromecanico',
  'Montador Mecánico',
  'Of. Cuadrilla Generales',
  'Operador Cargadero',
  'Operador de Maq. Viales',
  'Operador de Eq. de Izaje',
  'Operador de Planta',
  'Operador Descargadero',
  'Operador Manlift',
  'Pañolero',
  'Pasante',
  'Piloto',
  'Planificación y Control',
  'Project Manager',
  'Recorredor',
  'Representante Técnico',
  'Responsable de Compras',
  'Responsable de RRHH',
  'Secretaria',
  'Seguridad Patrimonial',
  'Señalero - Eslingador',
  'Sistemas Informáticos',
  'Soldador',
  'Supervisor Civil',
  'Supervisor de Obras',
  'Supervisor de Piping',
  'Supervisor de Producción',
  'Supervisor E&I',
  'Supervisor General',
  'Supervisor QA/QC',
  'Supervisor Servicio',
  'Tareas Generales',
  'Técnico HSE',
  'Técnico HSE Junior',
  'GGO.SIG',
  'Tesorero/a',
  'Topografía',
  'Transporte de Personal',
];

// Los 16 valores distintos de "Dependencia" en la nómina.
export const CENTROS_COSTO: string[] = [
  '1_ Administración',
  '2_ Taller',
  'Asistente Dirección',
  'Estructura Servicios',
  'LOG_Logística',
  'Mant. Edilicio H. Land',
  'OB308',
  'OB_ Estructura Obras',
  'S31',
  'S32',
  'S47',
  'S48',
  'S49',
  'S51',
  'S71',
  'SSMAC',
];
